lsi: false
hilighter: rogue
source: .
exclude: ["vendor", "lib", "Capfile", "Gemfile", "config", "log", "tmp", "CNAME", "README.md"]
destination: public
description: Addumb.com. It's just a crappy personal site. nbd. Move along.
permalink: /:year/:month/:day/:title/
url: http://addumb.com
